server:
  port: 9003

spring:
  application:
    name: menu-service
  datasource:
    url: jdbc:mysql://localhost:3306/menu
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

